font_family ComicCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11
copy_on_select yes
shell fish

# Better URL handling
detect_urls yes


# GPU rendering tweaks
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Faster scrolling
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 6.0

shell_integration no-cursor

# Cursor
cursor_shape     block
cursor_unfocused hollow
cursor_blink_interval 0


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
