alias v "nvim"
alias ll "exa -lah --icons"
alias ls "exa --icons"
alias cls "clear"
alias new "tmux new-session -A -s"
alias tls "tmux ls"
alias G "Godoc"
alias ff "fzf"
alias st "echo \$status"
alias inp "sudo apt install $1"
alias rmp "sudo apt autoremove --purge $1"
