set-option -g default-shell "/usr/bin/fish"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set-option -a terminal-features ",alacritty:RGB"
# Keymaps
unbind C-b

set -g prefix C-a
bind C-a send-prefix

bind C-v split-window -h
bind C-h split-window -v
unbind "%"
unbind "\""

bind C-k kill-pane

bind C-r source-file ~/.config/tmux/tmux.conf \; display-message "configs loaded"




bind h select-pane -L
bind j select-pane -D
bind l select-pane -R
bind k select-pane -U

bind m command-prompt -p "swap window to:" "swap-window -t '%%'"

bind r rotate-window
unbind C-o

unbind c
bind "'" new-window

unbind H
unbind L
unbind K
unbind J

bind H resize-pane -L +5
bind L resize-pane -R +5
bind K resize-pane -U +5
bind J resize-pane -D +5

bind - kill-pane

#source-file ${HOME}/.tmux-themepack/powerline/block/cyan.tmuxtheme

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# set -g @plugin "janoamaral/tokyo-night-tmux"

set -g @plugin 'TanglingTreats/tmux-everforest' # Adds to the list of plugins
set -g @tmux-everforest 'dark-medium' # Sets the option to select the theme. Also the default.
# Add '-xterm' to the back of the name for xterm256 compatibility
# E.g. 'dark-medium-xterm'
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-fail "false"
set-option -g @ssh-split-no-env "false"
set-option -g @ssh-split-no-shell "false"
set-option -g @ssh-split-strip-cmd "true"
set-option -g @ssh-split-verbose "true"
set-option -g @ssh-split-debug "false"
set-option -g @ssh-split-h-key "|"
set-option -g @ssh-split-v-key "S"
set-option -g @ssh-split-w-key "C"
set-option -g @ssh-split-r-key "R"

set -g @plugin 'pschmitt/tmux-ssh-split'
set -g @plugin 'pschmitt/tmux-ssh-split'


# set -g @tokyo-night-tmux_theme storm    # storm | day | default to 'night'
# set -g @tokyo-night-tmux_transparent 1  # 1 or 0
# Add '-xterm' to the back of the name for xterm256 compatibility
# E.g. 'dark-medium-xterm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


set -s copy-command 'xclip -in -selection clipboard'

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selectio
